add test to avoid log output
Signed-off-by: Lukas Harzenetter <lharzenetter@gmx.de>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,7 +22,15 @@ jobs:
     if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v2\
+      - name: Check if AbstractResourceTest does not cotain log().all().
+        run: |
+          if grep -i -q '\.all()' org.eclipse.winery.repository.rest/src/test/java/org/eclipse/winery/repository/rest/resources/AbstractResourceTest.java;
+          then
+            echo "Log output should be shortend. Use .ifValidationFails()!";
+            exit 1;
+          else
+            exit 0;
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
