Fix editable flag in Tenant mode (#621)
Signed-off-by: Lukas Harzenetter <lharzenetter@gmx.de>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,6 +23,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+      - name: Check if AbstractResourceTest does not cotain log().all().
+        run: |
+          if grep -i -q '\.all()' org.eclipse.winery.repository.rest/src/test/java/org/eclipse/winery/repository/rest/resources/AbstractResourceTest.java;
+          then
+            echo "Log output should be shortend. Use .ifValidationFails()!";
+            exit 1;
+          fi
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
